### ISSUE TITLE
Core bug "Cannot read property 'output' of undefined"

### ISSUE THREAD

**Issue by niftylettuce** [xojs/gulp-xo#18]
There's currently a bug on line 42-47 at <https://github.com/xojs/gulp-xo/blob/master/index.js#L42-L47> where `file.eslint` is undefined therefore `file.eslint.output` will throw an error `TypeError: Cannot read property 'output' of undefined`.  This has happened to me on multiple occassions with files that do not have any eslint output.

@sindresorhus

**Comment by niftylettuce** [comment]
@sindresorhus this is due to having an `.eslintignore` file with the particular file causing this error to be ignored, therefore it has no results array.

**Comment by atomless** [comment]
seeing this again whenever I specify quiet like so: ` .pipe(xo({ quiet: true }))`

**Comment by atomless** [comment]
here's the full error ```
[11:14:38] TypeError: Cannot read property 'output' of undefined
    at DestroyableTransform._transform (~/index.js:49:19)
    at DestroyableTransform.Transform._read (~/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (~/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (~/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (~/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (~/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at DestroyableTransform.ondata (~/node_modules/to-through/node_modules/readable-stream/lib/_stream_readable.js:619:20)
    at DestroyableTransform.emit (events.js:182:13)
    at DestroyableTransform.EventEmitter.emit (domain.js:459:23)
    at addChunk (~/node_modules/to-through/node_modules/readable-stream/lib/_stream_readable.js:291:12)
[11:14:38] 'lintJS' errored after 13 s
```
